# sfx_agent.yml
# Default settings for SamplePackAgent

# ElevenLabs sound‑effects model & voice
elevenlabs:
  voice: "sound_effects"
  model: "eleven_multisfx_v1"

# Ollama/Gemma settings
gemma:
  model: "gemma3:12b" # Make sure you have this model pulled in Ollama

# Output settings
output:
  folder: "./output_sfx" # Relative to config file location
  file_format: "wav"

# Prompt defaults & generation parameters
prompt:
  default_duration: 1.5       # seconds (fallback if not in decomposed params)
  prompt_influence: 0.8       # 0.0–1.0 (fallback if not in decomposed params)
  batch_influences: [0.6, 0.8, 1.0] # List of influences for variation generation

# Post-processing settings
processing:
  target_lufs: -18.0          # Target loudness for normalization

# Library settings
library:
  path: "prompt_library.yml"  # Relative to config file location

# Logging
logging:
  level: INFO                 # DEBUG, INFO, WARNING, ERROR, CRITICAL